/*
 * JS for playScreen generated by Appery.io
 *
 * Created on: Tuesday, April 30, 2013, 12:57:30 PM (PDT)
 */

/* Setting project environment indicator */
Appery.env = "bundle";

Appery.getProjectGUID = function() {
    return 'a8eac89a-4e17-471f-a802-5ee3941417cf';
}

Appery.getTargetPlatform = function() {
    return '0';
}

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Appery.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Appery.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

/*
 * Services
 */
var CameraService = new Appery.CameraService({});
youtubeService = new Appery.youtubeService({});
GenericService = new Appery.GenericService({});

//createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
Appery.AppPages = [{
    "name": "playScreen",
    "location": "playScreen.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}];

j_0_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'youtubePanel': 'j_4',
        'mobilenavbar_7': 'j_6',
        'mobilenavbaritem_8': 'j_7',
        'mobilenavbaritem_resultsOnPlay': 'j_8'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    Appery.CurrentScreen = 'j_0';

    /*
     * Nonvisual components
     */
    var datasources = [];

    youtubeServiceSource = new Appery.DataSource(youtubeService, {
        'onComplete': function(jqXHR, textStatus) {

            $t.refreshScreenFormElements("j_0");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [{
            'PATH': ['result'],
            'ID': '___js___',
            'TRANSFORMATION': function(value, element) {
                var query = localStorage.getItem('query');

                if (query !== null) {

                    var dataurl = 'http://gdata.youtube.com/feeds/api/videos?vq=' + escape(query) + '&orderby=relevance&alt=json&max-results=5';

                    $.get(dataurl).success(function(data) {
                        var results = data.feed.entry;
                        console.log(results.length);
                        for (var i = 0; i < results.length; i++) {

                            var videoId = results[i].id.$t.substr(42);
                            var autoplay = '';
                            if (i == 0) {
                                autoplay = '?autoplay=1';
                            }

                            $(Appery('youtubePanel')).append($('<iframe />', {
                                name: 'youTubeFrame',
                                id: 'youTubeFrame',
                                class: 'youtube-player" type="text/html',
                                style: 'border: 0',
                                width: '320',
                                height: '270',
                                src: 'http://www.youtube.com/embed/' + videoId + autoplay
                            }));

                            //alert(videoId);
                        }

                    });
                } else {
                    alert('please take picture first');
                    console.log("query is null");
                }
            },
            'SET': []
        }],
        'requestMapping': []
    });

    datasources.push(youtubeServiceSource);

    /*
     * Events and handlers
     */
    j_0_beforeshow = function() {
        Appery.CurrentScreen = 'j_0';
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }
    // screen onload
    screen_05B0_onLoad = j_0_onLoad = function() {
        screen_05B0_elementsExtraJS();

        j_0_windowEvents();
        screen_05B0_elementsEvents();
    }

    // screen window events
    screen_05B0_windowEvents = j_0_windowEvents = function() {
        $('#j_0').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });
        $('#j_0').bind({
            pageshow: function() {
                try {
                    youtubeServiceSource.execute({})
                } catch (ex) {
                    console.log(ex.name + '  ' + ex.message);
                    hideSpinner();
                };
            },
        });

    }

    // screen elements extra js
    screen_05B0_elementsExtraJS = j_0_elementsExtraJS = function() {
        // screen (screen-05B0) extra code

    }

    // screen elements handler
    screen_05B0_elementsEvents = j_0_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

        $('#j_5 [name="mobilenavbaritem_8"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('startScreen', {
                        reverse: false
                    });

                }
            },
        });

    }

    $("#j_0").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        j_0_beforeshow();
    });

    if (runBeforeShow) {
        j_0_beforeshow();
    } else {
        j_0_onLoad();
    }

}

$("#j_0").die("pageinit").live("pageinit", function(event, ui) {
    Appery.processSelectMenu($(this));
    j_0_js();
});