/*
 * JS for startScreen generated by Appery.io
 *
 * Created on: Tuesday, April 30, 2013, 12:57:30 PM (PDT)
 */

/* Setting project environment indicator */
Appery.env = "bundle";

Appery.getProjectGUID = function() {
    return 'a8eac89a-4e17-471f-a802-5ee3941417cf';
}

Appery.getTargetPlatform = function() {
    return '0';
}

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Appery.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Appery.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

/*
 * Services
 */
var CameraService = new Appery.CameraService({});
youtubeService = new Appery.youtubeService({});
GenericService = new Appery.GenericService({});

//createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
Appery.AppPages = [{
    "name": "playScreen",
    "location": "playScreen.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}];

j_11_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'targetImage': 'j_15',
        'mobilebutton_7': 'j_16',
        'mobilebutton_upload': 'j_17',
        'mobilenavbar_2': 'j_19',
        'mobilenavbaritem_3': 'j_20',
        'mobilenavbaritem_4': 'j_21'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    Appery.CurrentScreen = 'j_11';

    /*
     * Nonvisual components
     */
    var datasources = [];

    mobilecamera1 = new Appery.DataSource(CameraService, {
        'onComplete': function(jqXHR, textStatus) {

            $t.refreshScreenFormElements("j_11");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [{
            'PATH': ['imageDataBase64'],
            'ID': '___local_storage___',
            'ATTR': 'imageData'
        }, {
            'PATH': ['imageDataBase64'],
            'ID': 'targetImage',
            'ATTR': 'src'
        }],
        'requestMapping': [{
            'PATH': ['quality'],
            'ATTR': '40'
        }, {
            'PATH': ['destinationType'],
            'ATTR': 'Data URL'
        }, {
            'PATH': ['sourcetype'],
            'ATTR': 'Camera'
        }, {
            'PATH': ['allowedit'],
            'ATTR': 'true'
        }, {
            'PATH': ['encodingType'],
            'ATTR': 'JPEG'
        }, {
            'PATH': ['targetWidth'],
            'ATTR': '320'
        }, {
            'PATH': ['targetHeight'],
            'ATTR': '240'
        }]
    });

    datasources.push(mobilecamera1);

    /*
     * Events and handlers
     */
    j_11_beforeshow = function() {
        Appery.CurrentScreen = 'j_11';
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }
    // screen onload
    screen_3671_onLoad = j_11_onLoad = function() {
        screen_3671_elementsExtraJS();
        Appery('targetImage').css('margin', 'auto');

        j_11_windowEvents();
        screen_3671_elementsEvents();
    }

    // screen window events
    screen_3671_windowEvents = j_11_windowEvents = function() {
        $('#j_11').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });

    }

    // screen elements extra js
    screen_3671_elementsExtraJS = j_11_elementsExtraJS = function() {
        // screen (screen-3671) extra code

    }

    // screen elements handler
    screen_3671_elementsEvents = j_11_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

        $('#j_14 [name="mobilebutton_7"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    try {
                        mobilecamera1.execute({})
                    } catch (ex) {
                        console.log(ex.name + '  ' + ex.message);
                        hideSpinner();
                    };

                }
            },
        });
        $('#j_14 [name="mobilebutton_upload"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    var imageData = localStorage.getItem('imageData').substr(23);
                    //store the file and get permalink
                    var link;
                    $.ajax({
                        url: "http://ec2-75-101-253-28.compute-1.amazonaws.com:27017/upload.php",
                        type: "post",
                        data: {
                            "tell": imageData
                        },
                        success: function(data) {
                            if (data == "") {
                                alert("Image upload failed!");
                            } else {
                                console.log("--U--" + data + "---");
                                link = data;
                                //alert("Link: " + data);
                                ///////////////
                                //link = "files/b";
                                ///////////////
                                //console.log(encodeURIComponent("http://ec2-75-101-253-28.compute-1.amazonaws.com:27017/" + link));
                                //get google's best guess
                                $.ajax({
                                    url: "http://ec2-75-101-253-28.compute-1.amazonaws.com:27017/test.php",
                                    type: "get",
                                    data: {
                                        "img": "http://ec2-75-101-253-28.compute-1.amazonaws.com:27017/" + link
                                    },
                                    success: function(data) {
                                        if (data == "false") {
                                            alert("Error recognizing image");
                                        } else {
                                            console.log("--G--" + data + "---");
                                            //alert("Answer: " + data);
                                            if (data !== null {
                                                localStorage.setItem('query', data);
                                                Appery.navigateTo('playScreen', {
                                                    transition: 'slide'
                                                });
                                            } else {
                                                alert("no results fund for this image");
                                            }

                                            }
                                        }, error: function(data) {
                                            alert("Unknown error");
                                        }

                                    });

                                }
                            }, error: function(data) {
                                alert("Unknown error");
                            }

                        });

                    }
                },
            });

        $('#j_18 [name="mobilenavbaritem_4"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('playScreen', {
                        reverse: false
                    });

                }
            },
        });

        }

        $("#j_11").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
            j_11_beforeshow();
        });

        if (runBeforeShow) {
            j_11_beforeshow();
        } else {
            j_11_onLoad();
        }

    }

    $("#j_11").die("pageinit").live("pageinit", function(event, ui) {
        Appery.processSelectMenu($(this));
        j_11_js();
    });